version: '3.8'
services:
  web: 
   build: .
   ports: 
    - "3000:8080"
  db:
    image: postgres:13
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

volumes:
    db-data: